<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle("Bootstrap Layout"); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('DataTable/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('DataTable/css/bootstrap.css'))
    ?>

    <?php echo $this->headScript()
        ->prependFile($this->basePath('DataTable/js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('DataTable/js/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('DataTable/js/jquery-1.11.3.js'))
    ?>

</head>
<body>
<div class="container-fluid">
    <?php echo $this->content; ?>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
